[package]
name = "quo-subject"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "subject"
path = "src/main.rs"

[dependencies]
quo-arithmetic.workspace = true
quo-carriage.workspace = true
quo-envelope.workspace = true
quo-line.workspace = true
quo-notation.workspace = true
quo-warden.workspace = true
quo-wire.workspace = true
quo-zero.workspace = true
